### ISSUE TITLE
[EB][gaps] event-broker-sdk's "db" feature fails to compile standalone (requires "outbox" too)

### ISSUE THREAD

**Issue by striped-zebra-dev** [constructorfabric/gears-rust#4436]
Part of #4331.

## Problem Statement

`gears/system/event-broker/event-broker-sdk/Cargo.toml` declares:

```toml
db = ["dep:sea-orm", "dep:toolkit-db", "toolkit-db/sqlite"]
outbox = ["db", "toolkit-db/preview-outbox"]
```

implying `db` is usable on its own (e.g. by a consumer that only wants `LocalDbOffsetManager`/`TxSingleEventHandler`/`WithTx` and never touches the producer outbox). It isn't: `producer/db.rs:16` is gated only by `#[cfg(feature = "db")]` (see `producer/mod.rs:15-16`), but unconditionally does:

```rust
use super::outbox::{ProducerOutboxEnvelope, ProducerOutboxQueue};
```

and also references `toolkit_db::outbox::Partitions` and `super::partitioning::producer_outbox_partition` - all of which live behind the *separate* `#[cfg(feature = "outbox")]` gate (`producer/mod.rs:17-19`'s `mod outbox;`, `producer/partitioning.rs:23-24`). Building any crate with `event-broker-sdk = { features = ["db"] }` and NOT `"outbox"` fails to compile with three errors (`E0432` unresolved import, `E0433` cannot find `outbox` in `toolkit_db`, `E0425` cannot find function `producer_outbox_partition`).

Found while building `examples/event-broker/{fulfillment-service,notification-service}` (`event-broker-oop-example` OpenSpec change) - both gears only need `LocalDbOffsetManager` (pure `db`, no producer outbox at all), and enabling `features = ["db"]` alone failed to compile. Worked around by enabling `features = ["outbox"]` instead (which pulls in `db` transitively) even though neither gear uses any outbox API.

**Out of scope:** whether `outbox`'s own additional surface (`ProducerOutbox`, `DbProducer`, etc.) has any issues - this ticket is only about `db` failing to compile in isolation.

## Design / Proposed Solution(s)

*(for discussion)*

- Option A: split the outbox-specific pieces out of `producer/db.rs` so `db` alone compiles with just `LocalDbOffsetManager`/consumer-side code, and `outbox` layers the producer-outbox surface on top.
- Option B: make the Cargo.toml relationship explicit instead of accidental (`db` genuinely requires `outbox`'s internals) - simpler, but forecloses ever offering a lighter consumer-only DB feature.
- Leaning toward Option A since a consumer-only DB feature is a legitimate, smaller use case (exactly this example's need), but Option B is a one-line fix if the team doesn't want to invest in the split.
- **Open question:** was `db` without `outbox` ever exercised in CI? If not, a `cargo check --no-default-features --features db` build-matrix entry would have caught this immediately, regardless of which option is chosen.

## Definition of Done

- [ ] `cargo check -p cf-gears-event-broker-sdk --no-default-features --features db` succeeds (currently fails)
- [ ] CI has a build-matrix entry exercising `db` without `outbox`, so this can't silently regress
- [ ] Cargo.toml feature comments reflect the actual dependency relationship between `db` and `outbox`, whichever option is chosen

## Validation

- **Build verification:** the DoD's `cargo check` command is itself the acceptance test.
- **CI coverage:** the new build-matrix entry is the regression guard.

## References

- `gears/system/event-broker/event-broker-sdk/Cargo.toml` (`db`/`outbox` feature declarations)
- `gears/system/event-broker/event-broker-sdk/src/producer/db.rs:16` (unconditional `use super::outbox::{...}`)
- `gears/system/event-broker/event-broker-sdk/src/producer/mod.rs:17-19` (`#[cfg(feature = "outbox")] mod outbox;`)
- `gears/system/event-broker/event-broker-sdk/src/producer/partitioning.rs:23-24` (`producer_outbox_partition` gated by `outbox`)
- Observed live in `openspec/changes/event-broker-oop-example`, `examples/event-broker/{fulfillment-service,notification-service}/Cargo.toml` (local workaround: enabling `outbox` instead of `db`)
